### ISSUE TITLE
MIDI Tracks

### ISSUE THREAD

**Issue by RottenBlock** [kichikuou/system3-sdl2#1] opened 2020-05-11 23:59 UTC
Hello, just started to work with this. One thing I noticed is that System3-SDL produces very different-sounding MIDI tracks than the original games, including Takeda Toshiya's System3 for Win32. For example, Little Vampire plays nothing but piano, replacing the sound of other instruments with more piano.

It's possible the problem is with my computer's MIDI settings, so if you need me to get you more info or a recording, I can send that.

Is there any way to bring the sound closer to the originals?

**Comment by kichikuou** [comment] 2020-05-12 02:18
MIDI playback is one of the major things changed from the original System3 for Win32.

Takeda Toshiya used Windows' low-level MIDI API (`midiOutOpen`, `midiOutShortMsg`, etc.), which sends control messages to MIDI devices in real time using a worker thread. The sound comes from the Windows' built-in software synthesizer, if no physical MIDI device is connected.

System3-sdl2 converts MIDI control sequence to the Standard MIDI File format (also known as `.mid` file) instead of playing it in real time, because not all platform have a low-level MIDI API.

In Windows, the generated `.mid` data is then played using SDL_mixer. SDL_mixer has its own software synthesizer (probably with smaller data size than Windows built-in). That is why it sounds different.

To get sound from the Windows built-in synth, I think there are two options:

1. Play the generated `.mid` file using high-level API, such as [MCI](https://docs.microsoft.com/en-us/windows/win32/multimedia/mci), instead of SDL_mixer. Android and Emscripten ports of system3-sdl2 uses this approach.
2. Revive the original real-time MIDI control code, and use it only on Windows.

A downside of option 1 is that you won't get the seamless BGM loop, because you can't make a MIDI file of indefinite size. If BGM hiccups once every 3-5 minutes are acceptable, I prefer option 1 because of less platform-specific code.

I think I can work on this this weekend. Let me know what do you think on these options.

**Comment by RottenBlock** [comment] 2020-05-12 16:56
I worried it was something like that.  All considering, I think option 1 is the better option. It's true that there will be small hiccups, but it's rare that most games go that long without changing the music anyways (depending on reading speed). I suppose if you want you could keep the SDL_mixer version with a command-line argument? No sense letting it go to waste.

I should probably introduce myself while I'm here. I've been working on adding English support to System 3 for Win32. I was hoping to do the same with your version for wider system support.  All the work you've done here is extremely impressive, you've really accomplished a lot.

**Comment by kichikuou** [comment] 2020-05-13 09:05
OK, let me go with option 1.

I'm thinking of making it a compile time switch, in the same way as [`android/mako.cpp`](https://github.com/kichikuou/system3-sdl2/blob/master/src/android/mako.cpp) is used instead of [`sys/mako.cpp`](https://github.com/kichikuou/system3-sdl2/blob/master/src/sys/mako.cpp) when compiling for Android.

That also makes it possible to remove the SDL_mixer dependency. It would reduce the number of DLLs we have to bundle with System3 executable, as SDL_mixer comes with many DLLs (I guess some codec licenses prevent static linking).

The SDL_mixer version will still be used in Mac and Linux; it won't go to waste.

I just Googled your name and found your Wiki articles. Awesome works! I'm looking forward to see the English version of the games running on other platforms (especially on browsers).

**Comment by RottenBlock** [comment] 2020-05-13 21:40
A compile-time switch sounds like the right thing to do, I agree.

You're right about the number of DLLs, they can be such a mess! Though it makes me think: SDL_Mixer could be used for System 3 games with other music formats, couldn't it? In my Win32 port of the English translation of Rance 4.1 and 4.2, I added MP3 support via the Windows API, loading an external folder of MP3s. SDL_mixer is probably the best way to do that for a multi-platform release. But I guess I'm talking about a very different use case! As far as MIDI is concerned, I think you've got the right plan.

I'm excited to see the games in browsers, too! Adding Emscripten support was a great idea, so many possibilities. Unfortunately I don't have an Android phone to test the Android version. Do you know if the Android version currently works in any emulators?

**Comment by kichikuou** [comment] 2020-05-14 06:50
System3-sdl2 has similar MP3 support, with the [`-playlist` option](https://github.com/kichikuou/system3-sdl2#-playlist-filename). And yes, today it's implemented using SDL_mixer. I think reimplementing it for Windows will be trivial, because MIDI playback code could be mostly reused.

I haven't tried the Android version in emulators. Note that [released apks](https://github.com/kichikuou/system3-sdl2/releases) only include ARM native code, so it may be slow in emulators. If you don't mind building APK yourself, try enabling 'x86' and 'x86_64' [here](https://github.com/kichikuou/system3-sdl2/blob/master/android/app/build.gradle#L24).

**Comment by RottenBlock** [comment] 2020-05-14 18:26
Ah, great, that's even better then, I'll use that when I get to work.

Right, that makes sense about the Android version. I'll make sure to do that!

Good luck with the MIDI code!

**Comment by kichikuou** [comment] 2020-05-16 08:46
Now the Windows version uses MCI for MIDI playback (see the commit message of 9f5f4e6 for details). Let me know if there's anything wrong.

**Comment by RottenBlock** [comment] 2020-05-19 03:48
I'm afraid that, running the code on my machine anyways, the music still sounds the same as it did on the old setup. Is it likely I've done something wrong on my end?

**Comment by kichikuou** [comment] 2020-05-19 09:43
Ah, re-reading your first post, perhaps the issue is that `AMUS.MDA` file is not loaded correctly.

Since sounds for System1-3 games are originally for FM/PSG sound chips, `AMUS.DAT` does not have information on which MIDI instruments to use. `AMUS.MDA` defines that, and if it cannot be loaded [Piano is used](https://github.com/kichikuou/system3-sdl2/blob/dadf0aa/src/sys/mako_midi.cpp#L544) as default.

Do you have `AMUS.MDA` file in your game directory? Little Vampire downloaded from AliceSoft Archives has it. If you have it, can you confirm that [`dri->load()` here](https://github.com/kichikuou/system3-sdl2/blob/dadf0aa/src/sys/mako_midi.cpp#L572) returns a non-NULL value?

TOTO's System3 for Win32 embeds MDAs in the exe as [resources](https://en.wikipedia.org/wiki/Resource_(Windows)), and use that when MDA cannot be loaded from file. System3-sdl2 should do the same, but currently doesn't.

**Comment by RottenBlock** [comment] 2020-05-19 23:22
Ah, that's exactly it! I hadn't set up the MDA with the other data files, since I was used to it being loaded as a resource. That solves the problem! 

I feel silly for not realizing I had overlooked that. I'm sorry for all the fuss.

**Comment by kichikuou** [comment] 2020-05-20 09:46
I'm glad it was resolved. It was also a good opportunity for me to improve sound implementation on Windows :)

I'll make MDAs read from resource, and close this issue with that.

**Comment by RottenBlock** [comment] 2020-05-20 19:39
Thanks, glad the changes will still be helpful! It will be nice to have the MDAs as resources, so that sounds like a good plan as well.

**Comment by RottenBlock** [comment] 2020-10-12 21:45
Going to revive this temporarily. Because of the extra time it takes to generate MIDI data, I'm thinking it would be better to switch Windows to use the original MIDI code after all, while leaving the current MIDI code for other platforms. While the MIDI tracks generated are perfect, there's a visible delay on longer tracks. What do you think?

**Comment by kichikuou** [comment] 2020-10-13 09:52
MIDI generation is instant, but MIDI backend of MCI is very slow to load MIDI data. This `mciSendCommand()` call takes ~1000ms in my environment:
https://github.com/kichikuou/system3-sdl2/blob/master/src/win/mako.cpp#L72

Maybe system3-sdl2 is creating too much MIDI data. Currently it generates at least 50kb of data:
https://github.com/kichikuou/system3-sdl2/blob/master/src/sys/mako_midi.cpp#L47

By reducing `MIDI_SIZE_SOFT_LIMIT` to 20000, the time it takes in `mciSendCommand()` was reduced to <500ms. Do you think this is acceptable?

If we go back to the original approach (real-time MIDI control), I'd like to unify it with current `generate_smf` code instead of duplicateing the logic.

**Comment by RottenBlock** [comment] 2020-10-13 21:23
That is definitely an improvement. There are still noticable hiccups here and there, but the loading time is definitely halved on my end too. What are the downsides of changing MIDI_SIZE_SOFT_LIMIT?

**Comment by kichikuou** [comment] 2020-10-14 09:19
The smaller `MIDI_SIZE_SOFT_LIMIT`, the shorter the MIDI generated. Try setting it to 1000; the music will loop in a few seconds.
Hopefully we can find a sweet spot somewhere.

**Comment by RottenBlock** [comment] 2020-10-14 23:47
I'm going to try the 20000 value in a few games - I have to modify some of my localizations to work with the improved features in the new version and it takes a lot of beta-testing. I'll get back to you with my thoughts in a few days, hopefully.

**Comment by kichikuou** [comment] 2020-10-17 07:41
I've pushed two changes:

- bb9fc27 offloads slow MCI calls to a background thread, so that MIDI load won't delay subsequent command executions.
- 01608c8 removes the `MIDI_SIZE_SOFT_LIMIT` parameter. Now MIDI data is generated for the duration of one entire playback + 1-second fade out.

Can you try the latest code?

**Comment by RottenBlock** [comment] 2020-10-25 05:34
The lack of interruption is a big improvement, but I'm not sure about the single playback, especially with the short tracks in some games. I'd like to see how long it takes to generate with a second loop, how would I go about doing that?

**Comment by kichikuou** [comment] 2020-10-25 06:12
79b4efa adds a parameter for the minimum length of MIDI data to generate.

[This line](https://github.com/kichikuou/system3-sdl2/blob/master/src/win/mako.cpp#L111) loads the generated MIDI, which is the slow part. To see how long it takes, get timestamps before and after this line (e.g. using `GetTickCount()` API) and display the difference in a message box or console.

**Comment by RottenBlock** [comment] 2020-10-25 07:15
Thank you, that's helpful, even the current setting feels like a notable fix. Though I'm noticing some inconsistent results with certain tracks. For example, in Little Vampire, even if I set the value to something extremely high, only Track 5, a track that's normally 48 seconds, seems to be modified? The "Generated %d seconds of MIDI data" statement backs me up on this, giving me the same results for every other track no matter the setting.

Two other matters have come up through experimentation: using the Restart option now seems to crash on MCIThread::close(), the line DeleteFile(file_playing->c_str());. My IDE isn't giving me very helpful information as to why, so it might be its fault rather than the program. Are you seeing the same?

I'm not quite sure of the second thing. Am I right in saying that, when it comes to CD music, the game loads all tracks on boot instead when they're required? The boot period always seemed extra-long but there were no load times when tracks switched, so that's what I figured was happening. Now that you've changed things so that the game keeps going while music is loading, we end up with a fairly long period of silence in Rance 4.1, for example. What do you think about this?  I'm not 100% sure of the process so I'm not sure I should make any suggestions.

**Comment by kichikuou** [comment] 2020-10-25 08:19
`MINIMUM_MUSIC_DURATION` applies only to tracks that have loop information. Tracks with no loop info, `generate_smf()` stops generating at the end of the track. I think this explains why it has effect only for certain tracks in Little Vampire.

The restart menu command doesn't crash in my environment. What IDE/compiler are you using?

> Am I right in saying that, when it comes to CD music, the game loads all tracks on boot instead when they're required?

No, on boot only the playlist is loaded. MP3s are loaded just before playback, but unlike MIDI, they load very quickly.

> Now that you've changed things so that the game keeps going while music is loading, we end up with a fairly long period of silence in Rance 4.1, for example. What do you think about this?

Unfortunately, that silence period is inevitable as long as we use MCI to play MIDI. Possible solutions would be:

- Play MIDI in real time, using low-level API (to be honest I'm not interested in doing that), or
- Switch to other software MIDI synthesizer, i.e. SDL_mixer. Less platform-specific code, but more DLLs have to be distributed.

**Comment by RottenBlock** [comment] 2020-10-25 21:33
Ah, that would make sense, no problem then. I guess the feature's impact on LV will be minimal, but I'm favouring a minimum size of 9000 for the one track that applies at the moment.  Might be different for other games, I'll try some of them later today.

I'm using Code::Blocks 12207 on Windows. It also crashes randomly during system3-sdl2's quit routine in Debug builds (during the call to FreeConsole()), it's just sort of an irate program in general, I'm used to it at this point. I prefer Visual Studio but it can't use unistd.h.

If that's the case, it might be better to switch to SDL_mixer or whatever else you prefer. The end user's just not going to understand when the game opens to twenty seconds of silence, or what have you. Sorry if that's a big hassle.

**Comment by kichikuou** [comment] 2020-10-26 00:03
Wait, twenty seconds? The silence I'm observing is 0.2 sec or so.
Is it only at boot time or every time music is played?

**Comment by RottenBlock** [comment] 2020-10-26 00:19
Ugh, taking a look at it, it turns out that that's ALSO a CodeBlocks thing. It seems it was increasing the opening pause tremendously even in the Release build. This program is such a wreck. Running the executible outside of the IDE  gets the time down to about half a second, just like you said.  I didn't realize my IDE was causing so many problems, I'll make sure to check the standalone executible from here on out.  In that case there's no problem on that front.

In fact, with the previous fix covering the small audio file problem in Little Vampire, I think that covers all my concerns!

**Comment by kichikuou** [comment] 2020-10-26 09:44
Cool, let me close this issue.

The crash in `MCIThread::close()` was actually a bug; fixed in f4f8b7d.

**Closed by kichikuou** 2020-10-26 09:44 UTC
