### ISSUE TITLE
Rance 4.1: Mouse clicks on maps are not very responsive

### ISSUE THREAD

**Issue by silas1037** [kichikuou/system3-sdl2#14] opened 2021-08-27 16:31 UTC
In SysEng0.4, reactions on '前進する' could be quite soon so that you can move fast by contiously clicking, but system3-sdl2 is not.
When selection '前進する' appears, you have to wait 0.5 seconds until reacting to left-click.
In fact, not only moving selections, all selections seem so.

**Comment by kichikuou** [comment] 2021-08-28 03:04
System3 displays menu, waits 400 milliseconds, and then makes it selectable. This 400ms delay was [introduced](https://github.com/kichikuou/system3-sdl2/commit/5571061ac1ea96745d3bf7cd19374498aed1b508) in TOTO's upstream change in March 2020 (#2).

You can tweak this behavior by changing the value `400` in `NACT::wait_after_open_menu()` in `src/sys/nact.cpp`.

I'm not sure if we should just remove this delay. Without this, it's too easy for a user to accidentally select a menu item, especially after reading a long text by hitting the mouse button repeatedly.

**Comment by silas1037** [comment] 2021-08-28 17:31
I got it, thanks. 👍 
But now I got into another bug : (

https://github.com/silas1037/SysEng/commit/027be89d5cf3f8382e064dd2413f0c1b8ab5e24c

Because 0xeb9f～0xebfc，0xec40～0xec9e are used in GBK encoding but not in sjis, so I remap them into ff40~fffc, both in the scripts. But it crash before showing Loading Page.
Could you give some advise about gbk fixing?

**Comment by RottenBlock** [comment] 2021-08-28 21:54
The Rance 4.1 loading screen uses gaiji. Did you change the gaiji's hex value to match your changes? That may be the source of the problem.

**Comment by kichikuou** [comment] 2021-08-29 01:06
Can you send me your game files over an email? It's difficult to debug an issue without reproducing it locally.

**Comment by silas1037** [comment] 2021-08-29 01:46
> Can you send me your game files over an email? It's difficult to debug an issue without reproducing it locally.

Send.

**Comment by kichikuou** [comment] 2021-08-29 07:30
The crash was caused by a message with single gaiji character `'0xff5c'`.
Since the second byte `0x5c` is the backslash character in ASCII, the closing quote `'` was consumed as part of the message.

This is not a gaiji-specific nor GBK-specific issue, can happen in Shift-JIS games too. I created #15 for this bug.

**Comment by kichikuou** [comment] 2021-08-29 08:03
@silas1037 I've fixed the issue in this repository. Applying the changes in 201924f to your SysEng should resolve the crash bug.

**Closed by kichikuou** 2021-08-29 08:03 UTC

**Comment by silas1037** [comment] 2021-08-29 08:22
Thanks very much :)
